TECOSIM_AGENT_MAJOR_VERSION: int = 0
TECOSIM_AGENT_MINOR_VERSION: int = 0
TECOSIM_AGENT_UPDATE_VERSION: int = 5
MAJOR_COLOR1: str = "#FF9FF3"
MAJOR_COLOR2: str = "#54A0FF"
REASONING_COLOR: str = "#54A0FF"
TUI_REFRESH_RATE: int = 60
