"""TECoSim Agent constants"""
"""TECoSim Agent version"""
TECOSIM_AGENT_MAJOR_VERSION: int = 0
TECOSIM_AGENT_MINOR_VERSION: int = 0
TECOSIM_AGENT_UPDATE_VERSION: int = 10
"""Bash command risk"""
BASH_HIGH_RISK_LABEL = "BASH_HIGH_RISK"  # high-risk (0)
BASH_PACKAGE_LABEL = "BASH_PACKAGE"  # high-risk (0)
BASH_NETWORK_LABEL = "BASH_NETWORK"  # high-risk (0)
BASH_REMOVAL_RF_LABEL = "BASH_RECURSIVE_FORCED_REMOVAL"  # medium-risk (1)
BASH_REMOVAL_R_LABEL = "BASH_RECURSIVE_REMOVAL"  # medium-risk (2)
BASH_REMOVAL_F_LABEL = "BASH_FORCED_REMOVAL"  # medium-risk (2)
BASH_REMOVAL_LABEL = "BASH_REMOVAL"  # medium-risk (3)
BASH_CHMOD_LABEL = "BASH_LOW_RISK_CHMOD_OPERATION"  # low-risk (4)
BASH_CHOWN_LABEL = "BASH_LOW_RISK_CHOWN_OPERATION"  # low-risk (4)
BASH_FILE_LABEL = "BASH_LOW_RISK_FILE_OPERATION"  # low-risk (4)
BASH_REPOSITORY_MODIFY_LABEL = "BASH_REPOSITORY_MODIFY"  # medium-risk (5)
BASH_STAGE_CHANGE_LABEL = "BASH_STAGE_CHANGE"  # medium-risk (6)
BASH_UNKNOWN_LABEL = "BASH_UNKNOWN"  # unknown (7)
BASH_SAFE_LABEL = "BASH_SAFE" # no-risk (8)
BASH_EMPTY_LABEL = "BASH_EMPTY" # no-risk (9)
"""UI"""
MAJOR_COLOR1: str = "#FF9FF3"
MAJOR_COLOR2: str = "#54A0FF"
REASONING_COLOR: str = "#54A0FF"
EDIT_VIEW_RMV_BG: str = "#5F0000"  # remove line bg color
EDIT_VIEW_ADD_BG: str = "#005F00"  # add line bg color
EDIT_VIEW_LINE_MARGIN_SINGLE: int = 3
EDIT_VIEW_LINE_MARGIN_MULTI: int = 2
EDIT_VIEW_LEFT_SPACE_MARGIN: int = 5
EDIT_VIEW_LINE_SPACE_MARGIN: int = 1
URL_CACHE_VIEW_MAX: int = 8
URL_CACHE_CONTENT_CHAR_MAX: int = 100
